### ISSUE TITLE
Unable to execute it on my system

### ISSUE THREAD

**Issue by Abhishek9320** [7h3rAm/yml2dot#1]
@7h3rAm 

While running the code locally through PyCharm below is what I get.
I cloned your repo on my windows system running Python version 3.10.
Is there anything I am missing out on?
Kindly assist.

`$ python ./yml2dot.py -rcy test2.yml`
`The system cannot find the path specified.`

**Comment by 7h3rAm** [comment]
Looks like your Python binary location is not in system path? Can you share a screenshot with output for following commands:

`dir /b /s python.exe`
`echo %PATH%`

**Comment by 7h3rAm** [comment]
NA
